
jwt:
  secretKey: ${JWT_SECRET_KEY}

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

oauth:
  kakao:
    client_id: ${OAUTH_KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    client_id: ${OAUTH_NAVER_CLIENT_ID}
    client_secret: ${OAUTH_NAVER_CLIENT_SECRET}
    redirect_uri: http://localhost:3000/naverLogin
  google:
    client_id: ${OAUTH_GOOGLE_CLIENT_ID}
    client_secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect_uri: http://localhost:3000/googleLogin


spring:
  application:
    name: otoo_java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${SPRING_MAIL_HOST}
  config:
    name: secondtutorial
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-file-size: 200MB


fastapi:
  url: ${FASTAPI_URL}

react:
  url: ${REACT_URL}

rest:
  url: ${REST_URL}

data:
  redis:
    port: 6379
    host: localhost

server:
  port: 8080



management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

vito:
  client_id: ${VITO_CLIENT_ID}
  client_secret: ${VITO_CLIENT_SECRET}
#check
